### ISSUE TITLE
Fence crashes VCV instance in Bitwig when reopening a project.

### ISSUE THREAD

**Issue by Torinbob** [Stubs42/OrangeLine#14] opened 2021-12-02 12:11 UTC
Hi Deiter,

I am getting an issue in Bitwig where after I quit then reopen a Bitwig project, if the rack VST patch has Fence in it, then Rack crashes on startup when I reopen the project.

<img width="316" alt="Screenshot 2021-12-02 at 11 06 49" src="https://user-images.githubusercontent.com/41232273/144419248-920bd462-1498-42a1-9b7f-e99eef2870fb.png">

If I remove Fence from the patch, then the Rack VST loads fine on startup.

Adding Fence from the browser and using it in the patch is all working fine. The issue only happens after saving and quitting Bitwig then launching it again.

Regards,
Steve

**Comment by Stubs42** [comment] 2021-12-02 12:17
Hi,
I haven't tested using as VST yet. I also do not have bitwig.
Since I have no idea what is causing that I need some more information on that.
Which environment do you use  windows/linux/mac?
Is there any log file or similar giving a little hint on whats happening ?
Working with FENCE on the stand alone VCV works just fine on windows.
Any hint on what I can do is appreciated.
Regards
Dieter

**Comment by Stubs42** [comment] 2021-12-02 12:18
btw. does this happen with other orange line modules too?

**Comment by Torinbob** [comment] 2021-12-02 12:22
Hi just tested with other orange line modules too. It happens with dejavu, but all others are fine.

In fact I do not need to quit and restart Bitwig to get the issue - I can repeat it by deleting the Rack VST instance, and then undoing. Without fence or dejavu in the patch, the undo works fine, with them Rack immediately crashes when I undo.

I'm on Mac. I don't know about a log, I will take a look and see if I can find anything

You can get a free 30 unlimited time demo of Bitwig if that helps. You'll like Bitwig - it's awesome!

**Comment by Torinbob** [comment] 2021-12-03 11:33
Hi Dieter,

Antonio has been getting a similar crash on load and undo in the DAW with Nysthi.

He just replied to me:

"from what you are saying (crash on open, on UNDO, and let me guess, on DUPLICATE) the problem arise from a “dataFromJson”.

Does that help maybe?

**Comment by cschol** [comment] 2021-12-03 14:07
The issue has been confirmed to be related to font reference storage across frames (in any module that uses custom fonts).

Please see this link on how to properly implement this and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by Stubs42** [comment] 2021-12-03 22:53
Should be fixed now and already submitted to the library.
Thanks for your help finding the cause

**Comment by Stubs42** [comment] 2021-12-03 22:54
Please let me know whether the problem is fixed after 2.3.10 is available in the plugin library, so I can close this issue.

**Comment by cschol** [comment] 2021-12-04 01:07
Confirmed to not crash. Update released in Library.

**Comment by Stubs42** [comment] 2021-12-04 03:59
Thx for your support

**Closed by Stubs42** 2021-12-04 03:59 UTC
