### ISSUE TITLE
Fence is crashing Rack - Mac OS X

### ISSUE THREAD

**Issue by pgatt** [Stubs42/OrangeLine#1] opened 2019-10-15 00:35 UTC
Hi Dieter, 

Your module is crashing Rack upon selection in the module browser on Mac OS X.

Rack v 1.1.5

Log file linked below:
https://www.dropbox.com/s/yhs0177c4uus1rm/log%203.txt?dl=0

[log 3.txt](https://github.com/Stubs42/OrangeLine/files/3726893/log.3.txt)

**Comment by Stubs42** [comment] 2019-10-15 07:02
Hi,
Do not have a Mac System to test.
Did some small changes hoping it may help.
Fixed the widget size and check for null with if(mode != NULL) instead of if (mode).
Is there any way to get more info on what is happening on the crash ?
Can you please give it another try ?

**Comment by pgatt** [comment] 2019-10-15 07:18
No that's worse, cannot build it at all now.

c++  -std=c++11 -stdlib=libc++ -I./src -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/Fence.cpp.o src/Fence.cpp
src/Fence.cpp:1110:3: error: use of undeclared identifier 'w'
                w->box.size = mm2px (Vec(26, 7));
                ^
1 error generated.
make: *** [build/src/Fence.cpp.o] Error 1

**Comment by pgatt** [comment] 2019-10-15 07:19
Happy to test it for you on Mac as you need

**Comment by Stubs42** [comment] 2019-10-15 07:33
Sry, my fault.
Compile error should be fixed now.
Please use the 1.0.0 Branch for testing.
Any help to find out whats going on on mac is appreciated

**Comment by pgatt** [comment] 2019-10-15 08:08
That fixed the immediate crash upon bringing the module into Rack. It seemed to be working quite well until I hit the SHPR trigger.

Log file below again:

https://www.dropbox.com/s/f0cyqq4yzgbiqym/log%204.txt?dl=0

**Comment by pgatt** [comment] 2019-10-15 08:10
That crash corrupted my patch and upon starting a new patch bringing a module into the rack from the module browser crashes again.

https://www.dropbox.com/s/qvas55qdieiqqrf/log%205.txt?dl=0

**Comment by Stubs42** [comment] 2019-10-15 08:19
Did little changes in formatting the display.
Can you give the 1.0.0 another try ?

**Comment by pgatt** [comment] 2019-10-15 08:24
Still a-crashing. 

https://www.dropbox.com/s/dseiokiozndnla1/log%206.txt?dl=0

**Comment by Stubs42** [comment] 2019-10-15 08:27
Can try the following please:

add the line:
return pStr;
just below:
*pStr = '\0'; in line 1124
This should disable display drawing.
Just to check whether the problem is in cv2Str

**Comment by Stubs42** [comment] 2019-10-15 08:30
Just tried myself and got sometimes a crash too
even with the above change.
I'll investigate burther

**Comment by pgatt** [comment] 2019-10-15 08:39
Hang on, I may have still been using the default branch.

**Comment by pgatt** [comment] 2019-10-15 08:45
Still crashing after being on the 1.0.0 branch

https://www.dropbox.com/s/eamtgh9yn8ow9kc/log%207.txt?dl=0

**Comment by pgatt** [comment] 2019-10-15 08:46
What's your email? I can send you the Mac Crash report now that it raised one.

**Comment by Stubs42** [comment] 2019-10-15 08:46
dieter.stubler@googlemail.com

**Comment by pgatt** [comment] 2019-10-15 08:51
Sent. Did that help?

**Comment by Stubs42** [comment] 2019-10-15 08:52
Very Strange, happens on my Linux build also, but sporadically, so i assume an unitialized variable or a race condition.

**Comment by Stubs42** [comment] 2019-10-15 09:26
Hi,
have the following behaviour.
When running Rack from my own build it crashes after adding some Fences.
I'm on branch v1 'origin/v1'
git status in Rack src dir is showing me:
    geändert:       dep/glfw (neue Commits)
sry my system is german.
Don't now how to get rid of this git changed message.
Running Rack original Rack 1.5 (not my own build) I cannot reproduce the crashed even after adding a lot of Fences. 
Which Rack do you use ?
Own build or the offical download version ?

**Comment by Stubs42** [comment] 2019-10-15 09:58
Hi,
as mentioned I had also sporadic crashed adding Fence using my self compiled VCV Rack.
Now did the following:
cd src/Rack/dep
make clean
cd src/Rack
make clean
git submodule update --init --recursive
make dep
make
after doing this I could not reproduce the crash adding Fence any more.
So if you are running on a self built Rack, please check with the official release, just to make sure we are not hunting ghosts.

**Comment by pgatt** [comment] 2019-10-15 10:01
I’m fairly sure I’m using the default downloaded Rack.

**Comment by Stubs42** [comment] 2019-10-15 12:07
Hi,
after some digging I have a question.
Is there a problem to call configParam in process to change the min/max and default of a knob when changing mode ?

**Comment by pgatt** [comment] 2019-10-15 12:18
Hi Dieter,

Sorry no idea.

**Comment by Stubs42** [comment] 2019-10-15 13:13
Problem should be fixed now.
calling configParam aagain after the constructor was executed is not allowed.
Changed this according to Andrew, by just changing the existig paramQuantities member variables.
There are no crashed here on my side anymore.
So please give it a try once more and let me know whether it works so I can close this issue.

**Comment by pgatt** [comment] 2019-10-15 13:17
Which branch should I try?

**Comment by Stubs42** [comment] 2019-10-15 13:18
1.0.0 is the one to be released in plugin manager, so take this one.

**Comment by Stubs42** [comment] 2019-10-15 13:20
Thank you for showing me this problem which was not so obvious because it worked in my environment most of the time. Now it should be fixed with your help.

**Comment by pgatt** [comment] 2019-10-15 13:35
Yep, seems to be working completely correctly here.

**Comment by Stubs42** [comment] 2019-10-15 13:44
Thank you for showing me this problem which was not so obvious because it worked in my environment most of the time. Now it should be fixed with your help.

**Closed by Stubs42** 2019-10-15 13:44 UTC

**Comment by Stubs42** [comment] 2019-10-15 13:45
After replacing calls to configParam by changing parameterQuantity member variables it now works as expected and this issue was closed
